### ISSUE TITLE
Location and sign of FRAC_K adjustment 

### ISSUE THREAD

**Issue by bpbond** [COMPASS-DOE/grossMethane#16]
@kendalynnm In 376543c86b01b33faa3c2e0a5930a09ccfe963d7 you put this back into the linear model:

<img width="578" alt="Screen Shot 2022-10-03 at 5 52 31 AM" src="https://user-images.githubusercontent.com/1956468/193549640-dba506a6-5592-43ea-8ef5-d1aef26d12fe.png">

Let's discuss this morning!

**Comment by bpbond** [comment]
Hahaha and now the AP fits are, um, degraded 😄 

![ap_pred](https://user-images.githubusercontent.com/1956468/193551894-b8ebd374-c5fc-438c-9727-4bd70da4299b.png)

**Comment by kendalynnm** [comment]
Discussed this morning -> turns out to be not so much the return of FRAC_K to the log (although current thinking dictates that this should be excluded), rather extreme sensitivity of the model to order of magnitude of the input data, which went from 10^1 to 10^-4 with recent dilution factor correction
